### PR TITLE
Freenode -> Libera

### PR DESCRIPTION
**Pull request by tacerus**

### CODE REVIEW

**Review by Mikaela — COMMENTED** [review]
I think they prefer to be known either as Libera Chat or liberachat, judging by https://github.com/Libera-Chat/libera-chat.github.io/pull/61#issuecomment-850907785 and no one says the contrary. I am still looking into this though

**Comment by Mikaela** [comment]
I didn't find any directl/explicit statement on that on the website, however

* their [About Libera Chat](https://libera.chat/about) page and other pages refer to them as Libera Chat
* their [SASL instructions (when selfhosted)](https://libera.chat/guides/sasl#sasl-client-configuration) consistently refer to various spellings which do include the Chat part.

Additionally the domain `libera.net` belongs to an entirely different network, so I think it's better to refer to them as Libera Chat (or `liberachat`) whenever possible

**Comment by jlu5** [comment]
I agree with the above, Libera Chat is a more correct name (though in the bot you'd usually reduce it to `libera` or `liberachat` since network names can't contain spaces or ".")

Also I'd prefer if you rolled further changes into one PR so that the resulting commit can be easily squashed.

**Comment by jlu5** [comment]
Superseded by #97

**Pull request closed without merging**
